### ISSUE TITLE
Not able to launch your web app

### ISSUE THREAD

**Issue by patel99** [airavata-courses/TeamZenith#32]
Hi TeamZenith,

I have followed the instruction provided you to run Milestone-4. After deploying your tar file(ROOT.TAR), when I try to access the web app on localhost, nothing shows up. When I checked catalina logs, I got following error 

```
Mar 29, 2016 12:17:57 AM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component        [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:633)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:977)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1655)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded     container; nested exception is org.springframework.beans.factory.BeanCreationException: Error     creating bean with name     'com.stormpath.spring.boot.autoconfigure.StormpathWebMvcAutoConfiguration': Injection of autowired     dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException:     Could not autowire field: protected com.stormpath.sdk.client.Client    com.stormpath.spring.config.AbstractStormpathWebMvcConfiguration.client; nested exception is    org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stormpathClient' defined in class path resource   [com/stormpath/spring/boot/autoconfigure/StormpathAutoConfiguration.class]: Bean instantiation via  factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.stormpath.sdk.client.Client]: Factory method 'stormpathClient' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'stormpathClientApiKey' defined in class path resource [com/stormpath/spring/boot/autoconfigure/StormpathAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.stormpath.sdk.api.ApiKey]: Factory method 'stormpathClientApiKey' threw exception; nested exception is java.lang.IllegalStateException: Unable to find an API Key 'id', either from explicit configuration (for example, ApiKeyBuilder.setApiKeyId) or from fallback locations:

1) system property stormpath.apiKey.id
2) resource file path or URL specified by system property stormpath.apiKey.file
3) resource file path or URL specified by environment variable STORMPATH_API_KEY_FILE
4) environment variable STORMPATH_API_KEY_ID
5) default apiKey.properties file location /root/.stormpath/apiKey.properties.
```

**Comment by anujbhan** [comment]
hello Pratik, 
thank you pointing out this issue, forward me your mail ID, I will send an key file, which is to be placed in your home folder "%USERHOME%.stormpath\" for windows and "~/.stormpath/" for Linux.

**Comment by anujbhan** [comment]
I will update the instruction file right away.

**Comment by patel99** [comment]
patelprv@indiana.edu

**Comment by anujbhan** [comment]
I have sent the mail, keep the key confidential.

thanks,
Anuj Bhandar

**Comment by patel99** [comment]
I can see that your default apikey location is - 

"default apiKey.properties file location /root/.stormpath/apiKey.properties"

And not ~/.stormpath

Is there any config file where I need to change it?

**Comment by ajinkya-dhamnaskar** [comment]
Hello Anuj,

Please send me required files
adhamnas@umail.iu.edu

Thank you.
